---
title: "ADMH coding"
author: "Anton Tikhonenko"
date: "2024-11-08"
output: html_document
---

<style type="text/css">
body{
  font-family: Helvetica;
  font-size: 12pt;
}
/* Headers */
h1, h2{
  font-size: 16pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(openxlsx)
```

Первым делом подгрузим все нужные нам файлы:


```{r upload}


adsl_ds <- read.xlsx("./ADaM-like/ADSL.xlsx")

mh_ds <- read.xlsx("./SDTM/MH_MEDICALHISTORY.xlsx")

```

Поработаем с ADSL, вытащим оттуда переменные:


```{r adsl}
admhsl_ds <- 
  adsl_ds %>% 
  select( STUDYID,
 USUBJID,
 TRTP,
 TRTPN
)%>%
  mutate(TRTPN = as.integer(TRTPN))
 
```


```{r admh_selection}
mh_ds <-  mh_ds %>% 
  filter(MHCAT == 'Medical History')  %>%
  unite(USUBJID, STUDYID, SUBJID, sep = "-") 
mhsl_ds<- mh_ds %>%
  select(
    USUBJID,
    MHSEQ,
    MHCAT,
    MHTERM,
    MHDECOD,
    MHBODSYS
  ) 

```



```{r ds_dates}
dates_ds <- 
  mh_ds %>% 
  select(USUBJID, MHSEQ, MHSTDTC, MHENDTC, MHENRTPT) %>%
  
  mutate(
    # Преобразование MHSTDTC в нужный формат и добавление флага ASTDTF
    ASTDT = ifelse(grepl("^\\d{4}-\\d{2}$", MHSTDTC), paste0(MHSTDTC, "-01"),
                   ifelse(grepl("^\\d{4}$", MHSTDTC), paste0(MHSTDTC, "-01-01"), MHSTDTC)),
    ASTDT = ifelse(ASTDT != "", format(as.Date(ASTDT), "%d.%m.%Y"), ""),
    # Корректный расчет флага AENDTF
    ASTDTF = case_when(
          is.na(MHSTDTC) ~ "Y", # Полностью отсутствует дата
          grepl("^\\d{4}$", MHSTDTC) ~ "M", # Отсутствует месяц и день
          grepl("^\\d{4}-\\d{2}$", MHSTDTC) ~ "D", # Отсутствует день
          grepl("^\\d{4}-\\d{2}-\\d{2}$", MHSTDTC) ~ NA_character_, # Полная дата
          TRUE ~ NA_character_
        ),    
    
    # Преобразование MHENDTC в нужный формат и добавление флага AENDTF
    AENDT = ifelse(MHENRTPT == "ONGOING", "",
                   ifelse(grepl("^\\d{4}-\\d{2}$", MHENDTC), paste0(MHENDTC, "-01"),
                          ifelse(grepl("^\\d{4}$", MHENDTC), paste0(MHENDTC, "-01-01"), MHENDTC))),
    AENDT = ifelse(AENDT != "", format(as.Date(AENDT), "%d.%m.%Y"), ""),
    AENDTF = case_when(
      is.na(MHENDTC) ~ "Y",
      grepl("^\\d{4}$", MHENDTC) ~ "M",
      grepl("^\\d{4}-\\d{2}$", MHENDTC) ~ "D",
      grepl("^\\d{4}-\\d{2}-\\d{2}$", MHENDTC) ~ NA_character_,
      TRUE ~ NA_character_
    ),
    MHENRF = ifelse(MHENRTPT == 'ONGOING', 'ONGOING', '')
  ) 



ADMH <- NA
```

```{r joins}
ADMH <- left_join(admhsl_ds, mhsl_ds, by = "USUBJID")
ADMH <- left_join(ADMH, dates_ds )
ADMH <- ADMH %>%
  filter(!is.na(MHTERM) & MHTERM != "") %>%  # Исключение строк с пустым MHTERM
  select(
    STUDYID,
    USUBJID,
    TRTP,
    TRTPN,
    MHSEQ,
    MHCAT,
    MHTERM,
    MHDECOD,
    MHBODSYS,
    MHSTDTC,
    ASTDT,
    ASTDTF,
    MHENDTC,
    AENDT,
    AENDTF,
    MHENRTPT,
    MHENRF
  )
```



```{r}
write.xlsx(ADMH, "./ADaM-like/ADMH.xlsx")
```

